package main

import (
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"slices"
	"strings"
	"sync/atomic"
	"testing"
)

func TestTheRunnerDoesNotRelaunchASessionThatContinuedDuringItsUsageCheck(t *testing.T) {
	calls := takeoverSandbox(t)
	previousHost := activeHost
	t.Cleanup(func() { activeHost = previousHost })
	activeHost = "claude"
	sid := "late-builtin"
	now := float64(nowSec())
	reset := now - 280
	cwd := t.TempDir()
	before := []string{userPromptLine(reset-3600, "fix the parser"), apiErrorLine(reset - 3599)}
	transcript := writeTranscriptAt(t, cwd, before, reset-3599)
	fetches := &atomic.Int64{}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		fetches.Add(1)
		continued := strings.Join(append(before, userPromptLine(float64(nowSec()), "Usage limit reset, continuing automatically")), "\n") + "\n"
		if err := os.WriteFile(transcript, []byte(continued), 0o600); err != nil {
			t.Error(err)
		}
		_, _ = io.WriteString(w, limitsBody(2, now+5*3600, 20, now+3*86400))
	}))
	t.Cleanup(server.Close)
	t.Setenv("NOCTIS_USAGE_URL", server.URL)
	t.Setenv("CLAUDE_CODE_OAUTH_TOKEN", "lab")
	config := releaseConfig()
	config["fable"] = object{"source": "oauth"}
	config["resume"] = object{"mode": "headless", "prompt": "carry on"}
	mustWriteJSON(files.config, config)
	updateState(func(state object) {
		stateMap(state, "waits")[sid] = object{"kind": "stopfailure", "window": "five_hour", "label": "5h", "used": float64(100), "threshold": nil,
			"until": reset, "startedAt": reset - 3599, "resumeAt": reset + 270, "attempts": float64(0), "cwd": cwd, "transcript": transcript, "launchMode": "headless"}
	})

	resumeWait(sid, "")

	if fetched := fetches.Load(); fetched != 1 {
		t.Fatalf("the runner fetched usage %d time(s), want once", fetched)
	}
	if got := launchesOf(calls, sid); got != 0 {
		t.Fatalf("Claude Code's own continue resumed the session while the runner fetched usage, and the runner still relaunched it %d time(s), so two copies of the session run (journal %v)", got, journaledFor(sid))
	}
	if journal := journaledFor(sid); !slices.Contains(journal, "skip-launch") {
		t.Fatalf("the runner left no journal entry saying why it did not relaunch the session: %v", journal)
	}
	if wait := getMap(getMap(readState(), "waits"), sid); wait != nil {
		t.Fatalf("the wait of a session that already continued is still stored: %v", wait)
	}
}

func relaunchWithAnEntryWrittenDuringTheUsageCheck(t *testing.T, sid, kind, entry string) string {
	t.Helper()
	calls := takeoverSandbox(t)
	previousHost := activeHost
	t.Cleanup(func() { activeHost = previousHost })
	activeHost = "claude"
	now := float64(nowSec())
	reset := now - 280
	cwd := t.TempDir()
	before := []string{userPromptLine(reset-3600, "fix the parser"), apiErrorLine(reset - 3599)}
	transcript := writeTranscriptAt(t, cwd, before, reset-3599)
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		written := strings.ReplaceAll(entry, "{at}", transcriptStamp(float64(nowSec())))
		if err := os.WriteFile(transcript, []byte(strings.Join(append(before, written), "\n")+"\n"), 0o600); err != nil {
			t.Error(err)
		}
		_, _ = io.WriteString(w, limitsBody(2, now+5*3600, 20, now+3*86400))
	}))
	t.Cleanup(server.Close)
	t.Setenv("NOCTIS_USAGE_URL", server.URL)
	t.Setenv("CLAUDE_CODE_OAUTH_TOKEN", "lab")
	config := releaseConfig()
	config["fable"] = object{"source": "oauth"}
	config["resume"] = object{"mode": "headless", "prompt": "carry on"}
	mustWriteJSON(files.config, config)
	wait := object{"kind": kind, "window": "five_hour", "label": "5h", "used": float64(100), "threshold": nil,
		"until": reset, "startedAt": reset - 3599, "resumeAt": reset + 270, "attempts": float64(0), "cwd": cwd, "transcript": transcript, "launchMode": "headless"}
	if kind == "batch" {
		wait["hit"], wait["threshold"] = "threshold", float64(92)
	}
	updateState(func(state object) { stateMap(state, "waits")[sid] = wait })
	resumeWait(sid, "")
	return calls
}

func TestAnEntryClaudeCodeWritesItselfDuringTheUsageCheckKeepsTheRelaunch(t *testing.T) {
	stopHookSummary := `{"type":"system","subtype":"stop_hook_summary","timestamp":"{at}","hookCount":1}`
	cases := []struct {
		name  string
		kind  string
		entry string
	}{
		{"a stop hook summary", "stopfailure", stopHookSummary},
		{"a compaction boundary and its summary", "stopfailure", `{"type":"system","subtype":"compact_boundary","timestamp":"{at}"}` + "\n" + `{"type":"user","isCompactSummary":true,"timestamp":"{at}","message":{"role":"user","content":"This session is being continued from a previous conversation"}}`},
		{"a meta caveat", "stopfailure", `{"type":"user","isMeta":true,"timestamp":"{at}","message":{"role":"user","content":"Caveat: the messages below were generated by the user while running local commands."}}`},
		{"a stop hook summary during a paused batch", "batch", stopHookSummary},
	}
	for index, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			sid := fmt.Sprintf("housekeeping%d", index+1)

			calls := relaunchWithAnEntryWrittenDuringTheUsageCheck(t, sid, tc.kind, tc.entry)

			if got := launchesOf(calls, sid); got != 1 {
				t.Fatalf("%s written while the runner checked usage was taken for the session going on: the session was relaunched %d time(s), want 1, so the work stops (journal %v)", tc.name, got, journaledFor(sid))
			}
		})
	}
}

func relaunchWithEntriesWrittenBeforeTheRunner(t *testing.T, sid, kind string, entries []string) string {
	t.Helper()
	calls := takeoverSandbox(t)
	previousHost := activeHost
	t.Cleanup(func() { activeHost = previousHost })
	activeHost = "claude"
	now := float64(nowSec())
	reset := now - 280
	cwd := t.TempDir()
	lines := []string{userPromptLine(reset-3600, "fix the parser"), apiErrorLine(reset - 3599)}
	for _, entry := range entries {
		lines = append(lines, strings.ReplaceAll(entry, "{at}", transcriptStamp(reset+10)))
	}
	transcript := writeTranscriptAt(t, cwd, lines, reset+10)
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_, _ = io.WriteString(w, limitsBody(2, now+5*3600, 20, now+3*86400))
	}))
	t.Cleanup(server.Close)
	t.Setenv("NOCTIS_USAGE_URL", server.URL)
	t.Setenv("CLAUDE_CODE_OAUTH_TOKEN", "lab")
	config := releaseConfig()
	config["fable"] = object{"source": "oauth"}
	config["resume"] = object{"mode": "headless", "prompt": "carry on"}
	mustWriteJSON(files.config, config)
	wait := object{"kind": kind, "window": "five_hour", "label": "5h", "used": float64(100), "threshold": nil,
		"until": reset, "startedAt": reset - 3599, "resumeAt": reset + 270, "attempts": float64(0), "cwd": cwd, "transcript": transcript, "launchMode": "headless"}
	if kind == "batch" {
		wait["hit"], wait["threshold"] = "threshold", float64(92)
	}
	updateState(func(state object) { stateMap(state, "waits")[sid] = wait })
	resumeWait(sid, "")
	return calls
}

func TestAnEntryClaudeCodeWritesItselfBeforeTheRunnerStartsKeepsTheRelaunch(t *testing.T) {
	stopHookSummary := `{"type":"system","subtype":"stop_hook_summary","timestamp":"{at}","hookCount":1}`
	cases := []struct {
		name    string
		kind    string
		entries []string
	}{
		{"a stop hook summary", "stopfailure", []string{stopHookSummary}},
		{"a compaction boundary and its summary", "stopfailure", []string{`{"type":"system","subtype":"compact_boundary","timestamp":"{at}"}`, `{"type":"user","isCompactSummary":true,"timestamp":"{at}","message":{"role":"user","content":"This session is being continued from a previous conversation"}}`}},
		{"a stop hook summary during a paused batch", "batch", []string{stopHookSummary}},
	}
	for index, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			sid := fmt.Sprintf("before-runner%d", index+1)

			calls := relaunchWithEntriesWrittenBeforeTheRunner(t, sid, tc.kind, tc.entries)

			if got := launchesOf(calls, sid); got != 1 {
				t.Fatalf("%s written after the reset, before the runner started, was taken for the session going on: the session was relaunched %d time(s), want 1, so the work stops (journal %v)", tc.name, got, journaledFor(sid))
			}
		})
	}
}

func TestTheRunnerDoesNotRelaunchASessionThatWentOnBeforeItStarted(t *testing.T) {
	for index, kind := range []string{"stopfailure", "batch"} {
		t.Run(kind, func(t *testing.T) {
			sid := fmt.Sprintf("went-on%d", index+1)
			prompt := `{"type":"user","timestamp":"{at}","message":{"role":"user","content":"keep going"}}`
			answer := `{"type":"assistant","timestamp":"{at}","message":{"role":"assistant","content":[{"type":"text","text":"Carrying on with the parser."}]}}`

			calls := relaunchWithEntriesWrittenBeforeTheRunner(t, sid, kind, []string{prompt, answer})

			if got := launchesOf(calls, sid); got != 0 {
				t.Fatalf("the session went on in its own window after the reset, and the runner still relaunched it %d time(s)", got)
			}
			if journal := journaledFor(sid); !slices.Contains(journal, "skip-launch") {
				t.Fatalf("the runner left no journal entry saying why it did not relaunch the session: %v", journal)
			}
		})
	}
}
